version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
        NEXT_PUBLIC_BUCKET_API_KEY: ${NEXT_PUBLIC_BUCKET_API_KEY}
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - S_MAXAGE=${S_MAXAGE}
      - STALE_WHILE_REVALIDATE=${STALE_WHILE_REVALIDATE}
      - SAMPLER_RATIO=${SAMPLER_RATIO}
      - REDIS_URL=${REDIS_URL}
      - TYPING_TIMEOUT=${TYPING_TIMEOUT}
