import Head from "next/head";
import { motion } from "framer-motion";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { useSession } from "next-auth/react";
import { socket } from "~/utils/socket";
import { useEffect } from "react";
import React from "react";

interface Props {
  title: string;
  children?: React.ReactNode;
}

export default function Layout({ title, children }: Props) {
  const { status } = useSession();

  useEffect(() => {
    if (status === "authenticated" && !socket.connected) {
      socket.connect();
    } else if (status === "unauthenticated" && socket.connected) {
      socket.disconnect();
    }
  }, [status]);

  return (
    <>
      <Head>
        <title>{title}</title>
<<<<<<< HEAD
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
=======
        <meta name="description" content="Social App OSKM ITB 2023" />
        <link rel="icon" href="/favicon.ico" />
>>>>>>> 750548a8312e6a33d8d1751afb3497c87688027e
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
      >
        {children}
        {process.env.NODE_ENV !== "production" && (
          <div className="hidden md:block">
            <ReactQueryDevtools initialIsOpen={false} />
          </div>
        )}
      </motion.div>
    </>
  );
}
